---
- name: Use Redfish to Eject Virtual Media
  hosts: Redfish
  connection: local
  gather_facts: false

  collections:
    community.general

  tasks:
  - name: Get Virtual Media Information
    community.general.redfish_info:
      category: Manager
      command: GetVirtualMedia
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Show Results
    debug:
      var: result
      verbosity: 2

  - name: Set image path for future use
    set_fact:
      image_path: "{{ result.redfish_facts.virtual_media.entries[0][1][1].Image }}"

  - name: Display virtual media Image Information
    debug:
      var: image_path

  - name: Eject Virtual Media
    community.general.redfish_command:
      category: Manager
      command: VirtualMediaEject
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
      virtual_media:
        image_url: '{{ image_path }}'
      resource_id: BMC
 
  - name: Confirm ejection of the media device
    community.general.redfish_info:
      category: Manager
      command: GetVirtualMedia
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: newResult

  - name: display confirmation of ejection to the user
    debug:
      var: newResult   

